/*This module deletes all of the data files generated by a tag*/

// node imports
var fs = require('fs');

// delete the files corresponding to this tag
exports.run = function(tag, type){

    // the file names to delete
    var toDelete = [
      '/data/audio/'+tag+'.'+type,
      '/data/json/'+tag+'.json',
      '/data/seg/'+tag+'.seg',
      '/data/wav/'+tag+'.wav'
    ];

    // strip the last directory off
    var lastDirIndex = __dirname.lastIndexOf('/');
    var parent = __dirname.substring(0,lastDirIndex);

    // for every file to delete
    toDelete.forEach(function(path){

      // check that it exists
      fs.exists(parent+path, function(exists) {


        if(exists) {
          console.log('Deleting '+parent+path);

          // delete the file
          fs.unlink(parent+path);
        } else {

          console.log(parent+path+' not found, so not deleting.');
        }

      });

    });

}
