/*This module deletes all of the data files generated by a tag*/

// node imports
var fs = require('fs');

// delete the files corresponding to this tag
exports.run = function(tag, type, files){

    // the file names to delete
    var toDelete = [
      tag+'.'+type,
      tag+'.json',
      tag+'.seg',
      tag+'.wav'
    ];

    // if there are children, clean up the wavs and audio files, too
    if (files){
      var rawAudio = files.map(function(fileName){
        return fileName;
      });
      var wavs = files.map(function(fileName){
        // separate the file into it's name and extension
        var periodIndex = fileName.lastIndexOf('.');
        var tg = fileName.substring(0,periodIndex);
        return tg+'.wav';
      });
      console.log("deleting");
      toDelete = toDelete.concat(rawAudio).concat(wavs);
    }

    // for every file to delete
    toDelete.forEach(function(path){

      // check that it exists
      fs.exists('/tmp/'+path, function(exists) {


        if(exists) {
          console.log('Deleting '+path);

          // delete the file
          fs.unlink('/tmp/'+path);
        } else {

          console.log(path+' not found, so not deleting.');
        }

      });

    });

}
